[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true 

[fuzz]
runs = 5000
max_test_rejects = 100000

[rpc_endpoints]
#@note TODO: cleanup rpc mess in the .env and set a reference to it here
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/0tEgRM3c6GxiHEaBNMuva8eZJHwtREjG"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/Ap0CaQISkIwnmoD78Is_JVcSAehHFxYK"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
